# Generated by Django 5.0.7 on 2024-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_fullname_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default='USER', max_length=200),
        ),
    ]
